# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = JetBrain Mono Nerd Font
$textcol = rgb(236, 239, 244)

general {
    hide_cursor = false
    screencopy_mode = 1
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animations = fade, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = eDP-1
    path = screenshot
    blur_size = 4
    blur_passes = 6
	noise = 0.0117
	contrast = 2
	brightness = 0.9086
	vibrancy = -1#.696
    color = rgba(3b4252ff)
}

input-field {
    monitor = eDP-1
    size = 20%, 5%
    outline_thickness = 1
    inner_color = rgba(2e344080) # no fill

    outer_color = rgba(181a1c1ee) rgba(5e81acee) 45deg
    check_color = rgba(ebcb8bee) rgba(Vee) 120deg
    fail_color = rgba(bf616aee) rgba(d08770ee) 40deg

    font_color = $textcol
    fade_on_empty = false
    rounding = 10

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment if you wish to display a message during authentication
    check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor = eDP-1
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    color = $textcol
    font_size = 90
    font_family = $font

    position = 0, 100
    halign = center
    valign = center
}

# DATE
label {
    monitor = eDP-1
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    color = $textcol
    font_size = 25
    font_family = $font

    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = $LAYOUT[gb]
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}
